# Generated by Django 3.0.5 on 2022-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20221203_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='pizza',
            new_name='indiv_pizza',
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.TextField(max_length=100),
        ),
    ]
