# Generated by Django 3.0.5 on 2022-12-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_remove_comment_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_added',)},
        ),
    ]
