# Generated by Django 3.0.5 on 2022-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20221211_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_field',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
