# Generated by Django 3.0.5 on 2022-12-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_auto_20221211_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
